version: "3.8"

x-api: &api_env
  ApiDataSourceType: POSTGRESQL
  DatasourceHostname: postgresql-service
  DatasourceDatabase: ${TK_POSTGRESQL_DATABASE_NAME}
  DatasourceUser: ${TK_POSTGRESQL_USERNAME}
  DatasourcePassword: ${TK_POSTGRESQL_PASSWORD}
  GroupValidationType: DEX
  UserValidationType: DEX
  AuthenticationValidationType: DEX
  TerrakubeHostname: localhost
  AzBuilderExecutorUrl: http://terrakube-executor:8090/api/v1/terraform-rs
  PatSecret: ${PAT_SECRET}
  InternalSecret: ${INTERNAL_SECRET}
  DexIssuerUri: http://terrakube-dex:5556/dex
  StorageType: AWS
  AwsStorageAccessKey: ${TK_OUTPUT_ACCESS_KEY}
  AwsStorageSecretKey: ${TK_OUTPUT_SECRET_KEY}
  AwsStorageBucketName: ${TK_OUTPUT_BUCKET_NAME}
  AwsStorageRegion: ${TK_OUTPUT_STORAGE_REGION}
  AwsEndpoint: ${TK_OUTPUT_ENDPOINT}
  TerrakubeUiURL: http://localhost:3000
  spring_profiles_active: demo
  DexClientId: terrakube-app
  CustomTerraformReleasesUrl: "https://releases.hashicorp.com/terraform/index.json"
  TerrakubeRedisHostname: ${TK_REDIS_CONTAINER_NAME}
  TerrakubeRedisPort: 6379
  TerrakubeRedisPassword: ${TK_REDIS_PASSWORD}
  SERVICE_BINDING_ROOT: /mnt/platform/bindings

x-executor: &executor_env
  TerrakubeEnableSecurity: "true"
  InternalSecret: ${INTERNAL_SECRET}
  TerraformStateType: AwsTerraformStateImpl
  AwsTerraformStateAccessKey: ${TK_OUTPUT_ACCESS_KEY}
  AwsTerraformStateSecretKey: ${TK_OUTPUT_SECRET_KEY}
  AwsTerraformStateBucketName: ${TK_OUTPUT_BUCKET_NAME}
  AwsTerraformStateRegion: ${TK_OUTPUT_BUCKET_REGION}
  AwsEndpoint: ${TK_OUTPUT_ENDPOINT}
  TerraformOutputType: AwsTerraformOutputImpl
  AwsTerraformOutputAccessKey: ${TK_OUTPUT_ACCESS_KEY}
  AwsTerraformOutputSecretKey: ${TK_OUTPUT_SECRET_KEY}
  AwsTerraformOutputBucketName: ${TK_OUTPUT_BUCKET_NAME}
  AwsTerraformOutputRegion: ${TK_OUTPUT_BUCKET_REGION}
  AzBuilderApiUrl: http://terrakube-api:8080
  ExecutorFlagBatch: "false"
  ExecutorFlagDisableAcknowledge: "false"
  TerrakubeToolsRepository: https://github.com/AzBuilder/terrakube-extensions.git
  TerrakubeToolsBranch: main
  TerrakubeRegistryDomain: terrakube-registry
  TerrakubeApiUrl: http://terrakube-api:8080
  CustomTerraformReleasesUrl: "https://releases.hashicorp.com/terraform/index.json"
  TerrakubeRedisHostname: ${TK_REDIS_CONTAINER_NAME}
  TerrakubeRedisPort: 6379
  TerrakubeRedisPassword: ${TK_REDIS_PASSWORD}
  SERVICE_BINDING_ROOT: /mnt/platform/bindings

x-registry: &registry_env
  AzBuilderRegistry: http://terrakube-registry:8075
  AzBuilderApiUrl: http://terrakube-api:8080
  AuthenticationValidationTypeRegistry: DEX
  TerrakubeEnableSecurity: "true"
  DexIssuerUri: http://terrakube-dex:5556/dex
  TerrakubeUiURL: http://localhost:3000
  PatSecret: ${PAT_SECRET}
  InternalSecret: ${INTERNAL_SECRET}
  RegistryStorageType: AwsStorageImpl
  AwsStorageAccessKey: ${TK_OUTPUT_ACCESS_KEY}
  AwsStorageSecretKey: ${TK_OUTPUT_SECRET_KEY}
  AwsStorageBucketName: ${TK_OUTPUT_BUCKET_NAME}
  AwsStorageRegion: ${TK_OUTPUT_STORAGE_REGION}
  AwsEndpoint: ${TK_OUTPUT_ENDPOINT}
  AppClientId: terrakube-app
  AppIssuerUri: http://terrakube-dex:5556/dex
  SERVICE_BINDING_ROOT: /mnt/platform/bindings

x-ldap: &ldap_env
  LDAP_TLS_VERIFY_CLIENT: try
  LDAP_ADMIN_USERNAME: "admin"
  LDAP_ADMIN_PASSWORD: "admin"
  LDAP_ROOT: "dc=example,dc=org"
  LDAP_CUSTOM_LDIF_DIR: "/ldifs"

x-minio: &minio_env
  MINIO_ROOT_USER: ${TK_OUTPUT_ACCESS_KEY}
  MINIO_ROOT_PASSWORD: ${TK_OUTPUT_SECRET_KEY}
  MINIO_DEFAULT_BUCKETS: ${TK_OUTPUT_BUCKET_NAME}

x-ui: &ui_env
  REACT_APP_TERRAKUBE_API_URL: http://terrakube-api:8080/api/v1/
  REACT_APP_CLIENT_ID: terrakube-app
  REACT_APP_AUTHORITY: http://terrakube-dex:5556/dex
  REACT_APP_REDIRECT_URI: http://localhost:3000
  REACT_APP_REGISTRY_URI: http://localhost:8075
  REACT_APP_SCOPE: email openid profile offline_access groups
  JAVA_TOOL_OPTIONS: -Dcom.sun.security.enableAIAcaIssuers=true

services:
  terrakube-api:
    image: azbuilder/api-server:${TK_VERSION}
    container_name: terrakube-api
    environment:
      <<: [*api_env]
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-service

  terrakube-executor:
    image: azbuilder/executor:${TK_VERSION}
    container_name: terrakube-executor
    environment:
      <<: [*executor_env]
    ports:
      - "8090:8090"

  terrakube-registry:
    image: azbuilder/open-registry:${TK_VERSION}
    container_name: terrakube-registry
    environment:
      <<: [*registry_env]
    ports:
      - "8075:8075"

  terrakube-dex:
    image: ghcr.io/dexidp/dex:${TK_DEX_VERSION}
    container_name: terrakube-dex
    ports:
      - "5556:5556"
    volumes:
      - ./config-ldap.yaml:/etc/dex/config.docker.yaml

  ldap-service:
    image: bitnami/openldap:${TK_LDAP_VERSION}
    container_name: terrakube-ldap-service
    environment: *ldap_env
    volumes:
      - ./config-ldap.ldif:/ldifs/config-ldap.ldif

  minio:
    container_name: terrakube-minio
    image: docker.io/bitnami/minio:${TK_MINIO_VERSION}
    environment: *minio_env
    volumes:
      - 'minio_data:/data'

  redis-service:
    image: bitnami/redis:${TK_REDIS_VERSION}
    container_name: ${TK_REDIS_CONTAINER_NAME}
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${TK_REDIS_PASSWORD}
      - REDIS_MASTER_PASSWORD=${TK_REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'

  postgresql-service:
    image: docker.io/bitnami/postgresql:${TK_POSTGRESQL_VERSION}
    container_name: postgresql-service
    environment:
      - POSTGRESQL_USERNAME=${TK_POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${TK_POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${TK_POSTGRESQL_DATABASE_NAME}
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  minio_data:
  redis_data:
  postgresql_data:
